version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: user-service-postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: lst
      POSTGRES_PASSWORD: 123456
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user-service  # Dockerfile 所在目录
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userdb
      SPRING_DATASOURCE_USERNAME: lst
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - postgres

volumes:
  postgres_data:
