apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort # 修改 Service 类型
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082 # 显式指定 NodePort，也可以省略，让 Kubernetes 自动分配
  selector:
    app: product-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: product-service:1.0
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/productdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "lst"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"
