apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort # 修改 Service 类型
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081 # 显式指定 NodePort，也可以省略，让 Kubernetes 自动分配
  selector:
    app: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:1.0
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/userdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "lst"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"
